# 配置数据库
spring:
  datasource:
    url: jdbc:mysql://39.97.106.60/senior-mall?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 111111
  redis:
    database: 0
    host: 129.204.47.209
    port: 6379
    password: zjb123456
  snowflake:
    workerId: 1
    dataCenterId: 1


access-control-allow-origin-enable: true
access-control-allow-origin: infomany.cn

jwt:
  key: old-man-mall-service
token:
  expire:
    seconds: 86400